### ISSUE TITLE
pysc2.bin.replay_actions : Module not found "Queue"

### ISSUE THREAD

**Issue by Elirso** [deepmind/pysc2#10]
When i try to run replay_actions, i get this error : 

`File "C:\Python36\lib\site-packages\pysc2\bin\replay_actions.py", line 24, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'`

line used to run : 
`python -m pysc2.bin.replay_actions --replay <replay_path>` 
`python -m pysc2.bin.replay_actions --help`

**Comment by Inoryy** [comment]
This works fine for me with Python 3.6.1 on both Windows and Linux.

> ModuleNotFoundError: No module named 'Queue'

`Queue` is a built-in module in Python, this error could imply a faulty installation.

**Comment by Elirso** [comment]
Hm... I tried changing in the .py file the import Queue to import queue as Queue, it seems to work, but then I get multiple errors related to `ERROR:root:Trying to access flag sc2_verbose before flags were parsed.`

I might try to reinstall python then...

**Comment by Inoryy** [comment]
I recommend installing it via [Anaconda](https://www.continuum.io/downloads) and then executing Python commands in `Anaconda Prompt`.

**Comment by halflings** [comment]
@Inoryy : Are you sure there's a `Queue` module in Python 3.6? I think it was renamed to `queue`:

https://docs.python.org/3/library/queue.html

**Comment by JustinMBrown** [comment]
Ok I fixed the issue. As @halfglings said, the first issue is that python 3.6 uses the lower case "queue" rather than "Queue". If you insist on using 3.6, change the import to the lower case version, and also be sure to change the 2 other places in replay_actions.py where that class is called.

The second issue was the flag issue. The problem was that the flags were being accessed before they were parsed. As someone noted [here](https://github.com/google/python-gflags/issues/37), you have to "explicitly to tell flags library to parse argv before you can access FLAGS.xxx". Usually, app.run() takes care of that, but for whatever reason it didn't. 
To solve the issue, add:

`FLAGS(sys.argv)`

right under

`flags.mark_flag_as_required("replays")`

For me, FLAGS(sys.argv) ended up on line 48.

Hope that helps

**Comment by Inoryy** [comment]
Nevermind, I was running `python -m pysc2.bin.play --replay` to test replays, thought it executed `replay_actions` under the hood.  
Can confirm it's broken with `replay_actions` because of `Queue` -> `queue`.
