### ISSUE TITLE
Observation space indexing doesn't match action space indexing

### ISSUE THREAD

**Issue by pekaalto** [deepmind/pysc2#103]
First, thank you very much for this awesome repository!!

--------
I have noticed that the observation-space indexing is different in observation-space (numpy) and in action-space. If I select an (x,y)-point from observations and want to move there I need to do (y,x) in the action-arguments.

Please consider the script below which is adapted from the MoveToBeacon -scripted agent.
The problem is explained after `####### SEE HERE:` -line.

```
import sys
import numpy as np
from absl import flags
from pysc2.env import sc2_env
from pysc2.lib import actions
from pysc2.lib.features import SCREEN_FEATURES

FLAGS = flags.FLAGS
flags.FLAGS(sys.argv)

res = 32
no_op = [actions.FunctionCall(0, [])]
select_all = [actions.FunctionCall(3, [[0], [0, 0], [res - 1, res - 1]])]
move_action_id = 331
player_neutral = 3

env = sc2_env.SC2Env(
    map_name="DefeatRoaches",
    step_mul=8,
    game_steps_per_episode=0,
    screen_size_px=(res, res),
    minimap_size_px=(res, res),
    visualize=True
)

timestep = env.reset()[0]

for i in range(500):
    player_rel = timestep.observation["screen"][SCREEN_FEATURES.player_relative.index]
    beacon_loc = player_rel == 3
    move_available = move_action_id in timestep.observation["available_actions"]
    beacon_visible = beacon_loc.any()
    if not (move_available and beacon_visible):
        timestep = env.step(select_all)

    x_beacon, y_beacon = [int(np.mean(c)) for c in np.where(beacon_loc)]
    ####### SEE HERE:
    # So this is where the beacon is in observations...
    assert player_rel[x_beacon, y_beacon] == 3
    # But to move there we need to flip the coordinates to (y, x) !!
    a = [actions.FunctionCall(move_action_id, [[0], [y_beacon, x_beacon]])]
    
    timestep = env.step(a)[0]

    a = [actions.FunctionCall(0, [])]
    timestep = env.step(a)[0]
    if timestep.last():
        print("Episode finished with score %d" %
              timestep.observation["score_cumulative"][0])

env.close()
``` 

I am Not sure if this is really a bug but I think it's worth opening a topic.  Maybe can save the frustration what I experienced debugging from someone else.

**Comment by Adam-Volny** [comment]
This is a good insight but I'm afraid you've got it the other way around. I have been running your code in a debugger and I was checking how the x_beacon and y_beacon actually correspond to points on screen in the visualization. They are flipped, so x_beacon is the y coordinate and y_beacon is the x coordinate.

The reason for that is in the way the observations are presented. You have a 2D array in which every row corresponds to a row of pixels on the screen. This naturally brings about inverse index ordering. So the first index into the 2D observation array indexes the rows, and the row index on the screen correspond to the y-coordinate and the index within a row corresponds to the x-coordinate. So the ordering in the output is actually the way you'd expect it, it's just that the natural ordering on the observation array induces reverse indexing.

If they have done it in such a way that the x-index would be first and the y-index would be second, if you would simply print the array or look at it in a debugger, it would be transposed.

For clarity, try running the following script to see what I mean

```
import numpy as np

beacon_loc = np.zeros((8,8))

for i in range(5,8):
    for j in range(1,4):
        beacon_loc[i,j] = 1

print(beacon_loc)

x_beacon, y_beacon = [int(np.mean(c)) for c in np.where(beacon_loc)]

print('this is actually the y-coordinate {}'.format(x_beacon))
print('this is actually the x-coordinate {}'.format(y_beacon))
```

Just as a final note, this seems to be an issue when you are working with scripted agents but it didn't really apply for my case when using conv nets and a flattened spatial output (because flattening a 2D array and recomputing correctly the x,y coords from the 1D index gives you the right coordinates right away). So just think carefully about what you are using and what you need.

**Comment by pekaalto** [comment]
Hmm yes my explanation is little bit wrong when it comes to x,y and seems like you are right. 
However, I wanted to raise the question of mismatch between observation and action space.

I think this is especially problem when we work with flattening and unflattening the spatial space.  Let me try to clarify with example:

Consider agent where we have this logic:

```
selected_spatial_action_flat = np.argmax(flattened_spatial_output_from_convnet)
selected_spatial_action_flat_2d = np.unravel_index(selected_spatial_action_flat, screen_dimension)
```
Then correct action is 
```
actions.FunctionCall(move_action_id, [[0], selected_spatial_action_flat_2d[::-1]])
```
However the natural choice
```
actions.FunctionCall(move_action_id, [[0], selected_spatial_action_flat_2d])
``` 
will silently go to totally wrong place and the agent will never learn.

**Comment by tewalds** [comment]
You are right that the two have a different order. I'm not sure what is the right way to fix it though. All 3 options are confusing:
- images in normal y,x order and coordinates in normal x,y order means they are different
- images in transposed x,y means that printing the images will be confusing
- coordinates in transposed y,x order means passing the coordinates will be confusing
I could blame choices made by math hundreds of years ago, but that doesn't fix anything. I'm sure it could be better documented and would accept pull requests to that effect. Any other suggestions?

**Comment by Inoryy** [comment]
I can confirm this as well and fixing it makes the whole difference between RL agent unable to learn anything (understandably) and essentially solving a map in real time.
 
@tewalds I agree that it's not clear how to specifically fix it, but I think a big **NB!** somewhere in the docs or maybe even in main readme is a good first step.

**Comment by tewalds** [comment]
Ok, this documentation has been added to the docs, though only in the internal dev version for now. It'll get pushed with the next release once I get a few more features working.
