### ISSUE TITLE
Can I edit the Mini-map by myself?

### ISSUE THREAD

**Issue by WoodLing** [deepmind/pysc2#107]

**Comment by WoodLing** [comment]
Does anyone know?

**Comment by SoyGema** [comment]
Hi @WoodLing !
Yes, you can edit the mini-game map from the SC2 editor 
You might find it in your Starcraft II folder - it was a cool green icon -
**Applications > Starcraft II > Starcraft II Editor.** 
Once there in open file you can open and/or edit . Let me know if I can help with a particular change .
Thanks!

**Comment by andrewliao11** [comment]
Hi @SoyGema,
Thanks for the pointer. Is there any released Editor fir Linux?

**Comment by SoyGema** [comment]
Hey @andrewliao11 !
From a quick search from [here](https://us.battle.net/forums/en/sc2/topic/20767596697) and [here](https://www.sc2mapster.com/forums/general/general-chat/139987-sc2-editor-possible-on-linux) , it doesn't seem to be a version for linux, but I'm not really sure .

However, running it from a virtual machine seems to be the fix for the situation.

Let me know if you found a better fix.
