### ISSUE TITLE
Mineral shards generation in mini game

### ISSUE THREAD

**Issue by sumitsk** [deepmind/pysc2#188]
The mineral shards in CollectMineralShards mini-game are generated randomly in every episode. Is it possible to specify the number and location of these shards instead of generating them randomly?

**Comment by tewalds** [comment]
That is defined in the map, so you'd have to create a new map. @SoyGema may be able to help or at least point you in the right direction if you're interested in pursuing it.

**Comment by SoyGema** [comment]
Hi there @sumitsk ! 
As far as I assume, CollectMineralShards makes the effort to propose an environment set for a machine problem like the [Vehicle routing problem](https://en.wikipedia.org/wiki/Vehicle_routing_problem) or other kind of variation the [Salesman Problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem). The randomly placed mineral shards has some sense, as the agent  goal is to learn an optimal route , because it is meant to be solved in every situation. If you always give the same path, it won't be able to solve different situations , or your agent won't be able to generalize well. 

With that in mind, I will answer your given question

- How can I place a given Item in a point in the SC2 editor in the map CollectMineralShards ? 

In the Terrain interface, you might find an orange menu in the top bar , next to region, you can find a point. Place one point in the editor and rename it.
<img width="160" alt="captura de pantalla 2018-05-30 a las 9 13 28" src="https://user-images.githubusercontent.com/24204714/40705696-de91327e-63eb-11e8-95c8-c61b0a0cc807.png">

In the trigger menu (Init script) you shall find a variable (blue) that in the original map is related to a Region . You might want to change it to Point 

<img width="683" alt="captura de pantalla 2018-05-30 a las 9 16 09" src="https://user-images.githubusercontent.com/24204714/40705809-3544d10c-63ec-11e8-8e9a-a8b536309cf4.png">

Ta-dá! 👍 

HINT : Machine Learning has a huge conceptual  load that affects environment design .
Don't give up , and find passion in the problem and not only on the solutions . 
Happy map editing!

**Comment by sumitsk** [comment]
Thank you @SoyGema for your help. I have one follow up question. Is it the case that the minerals can be placed at either random location or some pre-specified location which remain constant across resets? I have an application for which I require that the minerals position change across resets as specified by an external script. Is it possible for the SC2Map file to communicate with an external script that specifies the position to place minerals when we call the reset method?

**Comment by SoyGema** [comment]
Ey @sumitsk  !

- _Is it the case that the minerals can be placed at either random location or some pre-specified location which remain constant across resets?_  So is the question that if ' the Salesman problem is designed in this environment with random placement of items?' I think so, and the random location during training is relevant  . If not,  Can you reformulate  the question? 

- Is it possible for the SC2Map file to communicate with an external script that specifies the position to place minerals when we call the reset method?

I don´t really know.  In the trigger interface , if you press command+F11 a map script interface will open in which you can see a scripted version of your map . I would explore if your script and that one might integrate somehow . I am actually starting to produce some maps and testing them from there.

With your permisssion If I might ask ,
Are you trying to apply the Salesman problem with a specific 'route' with #pysc2 ? Because if that´s what you are searching for, you could use a pretrained agent, place the points and run it . 

Would be awesome if you might share how your integration goes ^^
