### ISSUE TITLE
Screen feature unit_type scale

### ISSUE THREAD

**Issue by baiztencale** [deepmind/pysc2#246]
Hey guys,

I am wondering why the scale of screen feature unit_type is set as:
`unit_type=(max(static_data.UNIT_TYPES) + 1, FeatureType.CATEGORICAL, colors.unit_type, False),`
in file pysc2/lib/features.py

Especially because the list `static_data.UNIT_TYPES` only contains 236 ids and there are also only 236 ids listed in the file pysc2/lib/units.py

Does pysc2 really use all `max(static_data.UNIT_TYPES) + 1` unit type ids, which are right now 1914?

**Comment by tewalds** [comment]
Those ids aren't densely packed, so the scale contains the full range. You can remap them into a smaller set of ids if you'd like, but the game won't understand those, so you'll need to map them back. Similarly there are a few hundred abilities used in the multiplayer game, but they span a range of 3600+ since many are specific to the single player or are no longer used. lib/actions.py remaps them into a smaller range, but I haven't done that for units.

**Comment by baiztencale** [comment]
I figured out `that static_data.UNIT_TYPES` as well as pysc2/lib/units.py do not contain the following ids:

- 317 - Beacon
- 1680 - Mineral shard

Maybe you could consider adding them to these.

It would be great to have a list (like `static_data.UNIT_TYPES`) where all posible values that can occoure in feature unit_type are listed, which i guess would be far less than `max(static_data.UNIT_TYPES) + 1`.

With this the feature pre-processing and neural network architecture could be optimizer further.
