### ISSUE TITLE
Examples Request

### ISSUE THREAD

**Issue by yukang2017** [deepmind/pysc2#28]
Hi!
Would you please give us some examples on how to train an agent in mini-games or other games?
Such as an actor-critic agent using tensorflow?
Thank you very much in advance!

**Comment by jvanelteren** [comment]
yes, I'm also looking for this! It would greatly clarify how it could for, for example a thing I am struggling with is where to find the logged scores of the actions when you would start the training.

**Comment by tewalds** [comment]
Unfortunately we can't open source our more advanced agents since they depend on a ton of internal libraries. Take a look at the example random or scripted agents for how to take the observation and generate actions though. Hopefully someone can use those examples with an open source implementation of a3c or similar to build some better example agents. I'd be happy to merge a better example agent if it's small and self-contained, or point to external examples.
