### ISSUE TITLE
Human play against the trained model

### ISSUE THREAD

**Issue by jackfong123** [deepmind/pysc2#289]
I've trained a model and it's performed better than the basic AI of StarCraft2. However, I want to test the model myself, but I cannot find the way. If someone know how to do,please let me know.Thanks!

**Comment by Ashargin** [comment]
Hello, take a look at https://github.com/deepmind/pysc2/blob/master/README.md#play-the-game-as-a-human in the documentation.
I think it probably means that what you ask is not possible.

**Comment by KingKeet** [comment]
`python -m play_vs_agent --human --map NameOfMap` for the human host

Agent is similar, but requires more variables to set the environment up for the agent

**Comment by WorksWellWithOthers** [comment]
> `python -m play_vs_agent --human --map NameOfMap` for the human host
> 
> Agent is similar, but requires more variables to set the environment up for the agent

Question, what do you mean by similar?
Is it my custom model or a pre-trained model?

**Comment by KingKeet** [comment]
The format is similar, but the flags are different. There are some missing flags for things like using raw data, but for the most part you need `--agent AgentName` instead of `--human` and flags used to set up the environment.

[This code](https://github.com/deepmind/pysc2/blob/master/pysc2/bin/play_vs_agent.py) is what you're running when you run these commands in the command line.

Also, you may have to run this on two separate machines, with the human host being set up first.

**Comment by WorksWellWithOthers** [comment]
Perfect. This is exciting. I'm getting back into SC2 and thought it would be fun to see if I can get a model trained up before I catch up to where I left off. I guess the bot will have the advantage in hours. Thank you so much.
