### ISSUE TITLE
How to run agent with basic ascii renderer?

### ISSUE THREAD

**Issue by KingKeet** [deepmind/pysc2#311]
I noticed in the notes for the release v3.0 tag that there's a basic ascii renderer and, this is the first time I've really noticed that it exists. Figuring out how to use it would be huge as far as reducing strain on my computer, so if anyone knows how to get the game to run with that I'd be grateful if you could let me know

**Comment by Nickrader** [comment]
https://github.com/deepmind/pysc2#run-the-tests
You'll see it print to standard output if you run the tests.
The tests seem to run alphabetically from the pysc2\lib folder.

pysc2\tests\replay_obs_test is where it gets called.
pysc2\lib\renderer_ascii is the library folder.

The test shows it [printing to stdout](https://i.imgur.com/pHnE57y.png).  I am unsure if this gets it's own window using the headless version?  I don't think there is a way to turn off the graphics in Windows version.  My assumption is it's used in the observer replay test, because that would be it's main use (not clickable, moveable, etc.)  But I couldn't figure too much out about it.

**Comment by tewalds** [comment]
Yeah, the ascii renderer is mainly there to debug in tests. You can't disable the graphics on windows/mac.
