### ISSUE TITLE
Difference btwn Attack_screen and Attack_Attack_screen?

### ISSUE THREAD

**Issue by phraust1612** [deepmind/pysc2#35]
Firstly, I really appreciate that you opened this great API to us.
By the way, I found very similar actions while their ids are different -
Attack_screen (12) and Attack_Attack_screen (14).
Similarly, there are also Attack_minimap (13) and Attack_Attack_minimap (15)

I wonder what is different between those.
Thank you.

**Comment by tewalds** [comment]
Any ending in _screen take a point on the screen, whereas those ending in _minimap take a point on the minimap. Since those can be different resolutions and have similar but different effects they're split into different functions.

Attack_screen vs Attack_Attack_screen is general vs specific. An easier example is Burrow where each unit that can burrow has its own ability, but they're all very similar so there's a general Burrow. It turns out there are a few versions of attack as well (eg for units in a bunker, or for support units like a medivac) that are a bit different than a normal attack, but that are conceptually similar enough to merge into a general Attack.

**Comment by phraust1612** [comment]
@tewalds Thank you!
