### ISSUE TITLE
Question about Starcraft 2 Versions

### ISSUE THREAD

**Issue by Eric-Wallace** [deepmind/pysc2#46]
Recently Blizzard has announced a major patch that is currently being beta tested. This patch would change some of the gameplay of SC2 and deprecate old replays and trained bots. Are we save to assume this API project will always stay up to date to the latest patch?

**Comment by Inoryy** [comment]
Related: https://github.com/Blizzard/s2client-proto/issues/30

**Comment by tewalds** [comment]
Replays are always version specific, so nothing will change there. The viable strategies already change as Blizzard releases data/balance patches. Even minor changes like reducing hit points of a single unit by 20% can have pretty big changes at the professional level. I suspect it'll be a long time before any agents are strong enough for that to make a big difference though. The major patch will definitely mean retraining or at least refining if you've figured out some advanced strategies that no longer work.

As the game changes we'll have to add new actions corresponding to the new unit abilities. I'm planning to leave the old ones in to keep compatibility with the old versions. Actions that are removed shouldn't break anything since there are already many actions that are never valid (eg actions for some other race, or specific actions). This is a good reason to not assume there will always be exactly the same number of actions as now though.

**Comment by Eric-Wallace** [comment]
Good point about leaving the actions in without breaking anything. Thanks for the response.
Closed.
