### ISSUE TITLE
How do I get the valid action space for a particular mini game map?

### ISSUE THREAD

**Issue by doudoujay** [deepmind/pysc2#56]
I know we could use "available_action" to get the result dynamically, is there a way to get the static valid action space for a mini game map?

Also, same question for Unit Type Feature map, the input could be huge regarding to 1850 different unit type, can we get certain unit type for certain mini game map?

**Comment by tewalds** [comment]
No, there is no way to get a static list of valid actions because that would only make sense if you only have one type of unit that can't be killed and it is always selected. If you want the subset of actions that are valid, try playing the random agent which should log all actions that it finds are ever valid. Of course on a complicated map it's unlikely to find them all.

You can get the full list of units from RequestStaticData, or just look up the ones that are common here: https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_typeenums.h
