### ISSUE TITLE
pysc2.maps.lib.NoMapException: Map doesn't exist: <My-Mini-Game-Map> in Mac

### ISSUE THREAD

**Issue by SoyGema** [deepmind/pysc2#63]
I have already created My-Mini-Game-Map.sc2map and add it to Applications/StartCraft2/Maps/mini-games folder and also in <path>/pysc2/maps/mini-games too.
When executing agent python3 -m pysc2.bin.agent --map <My-Mini-Game-Map> the error is given by

> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/site-packages/pysc2/bin/agent.py", line 112, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.6/site-packages/pysc2/lib/app.py", line 57, in run
>     really_start(main or sys.modules["__main__"].main)
>   File "/usr/local/lib/python3.6/site-packages/pysc2/lib/app.py", line 51, in really_start
>     sys.exit(main(argv))
>   File "/usr/local/lib/python3.6/site-packages/pysc2/bin/agent.py", line 87, in main
>     maps.get(FLAGS.map)  # Assert the map exists.
>   File "/usr/local/lib/python3.6/site-packages/pysc2/maps/lib.py", line 136, in get
>     raise NoMapException("Map doesn't exist: %s" % map_name)
> pysc2.maps.lib.NoMapException: Map doesn't exist: <My-Mini-Game-Map>

I have tried 
--with another sample of mini-games map given by default samples and works perfectly 
-- Ask for map list by python3 -m pysc2.bin.map_list and <My-Mini-Game-Map> does not appear

Do you know how can I solve this issue?
Wich step did I miss?

Thanks for this project !!

**Comment by KevinCalderone** [comment]
I think you need to go into "pysc2\maps\mini_games.py" and add your map name to the "mini_games" array.

**Comment by SoyGema** [comment]
Already did it and it is not working in both appearing into map_list or running .
Is it needed to reinstall or compile? 
Thanks

**Comment by KevinCalderone** [comment]
hmm doing that made it work for me. It is also strange how in the last line of your output "map_name" seems to be an empty string.

You also don't have the map name in the command line you posted, but I assume you were doing this:
python3 -m pysc2.bin.agent --map My-Mini-Game-Map

Another thing I just noticed is that it doesn't seem to work if you have dashes in the map name. Does it work if you rename your map "MyMiniGameMap"?

**Comment by SoyGema** [comment]
Hi there!
I renamed the mini-game map without dashes , edited the array at "pysc2\maps\mini_games.py"
and yes, posted python3 -m pysc2.bin.agent --map MyMiniGame
still not working . 

In the Starcraft II Editor it works when executing Test Document and the file is saved as MyMiniGame.SC2Map

Thanks for the attention dedicated to solve this issue

**Comment by KevinCalderone** [comment]
If all else fails, you can probably at least test you map by making it have the same name as one of the existing ones :(

It seems like it would be useful if PySC2 let you just specify the absolute path to the map.

**Comment by tewalds** [comment]
Is it failing to find the map python instance, or the map file? The error you posted above suggests that it can't find the map python instance, which is likely due to the dashes. If it can then find the python instance but not the file, then make sure it's in the expected location.

You can try changing https://github.com/deepmind/pysc2/blob/master/pysc2/maps/lib.py#L86 from e.filename to self.path to see if that gives a better error message of where it expects the file to be.

The reason it doesn't just let you specify an absolute path to the map file is that there's extra configs for whether the map is single/multiplayer, what time limits to use, etc. I guess as more of that gets moved into the map itself that may not be needed anymore, but that's for the future.

**Comment by tewalds** [comment]
I assume you got this working. Feel free to reopen if you're still having problems.

**Comment by ishandutta2007** [comment]
Where should I place the maps, the instruction is not clear?
for example if I place the `mini_games` maps under:
`C:\Program Files (x86)\StarCraft II\Maps\mini_games` they work fine but 
when I place the `Ladder2017Season1` maps under:
`C:\Program Files (x86)\StarCraft II\Maps\Ladder2017Season1` they dont.
I have also  tried placing the maps directly under `C:\Program Files (x86)\StarCraft II\Maps`, it still doesn't.

In either cases I get error:

> pysc2.maps.lib.NoMapException: Map doesn't exist

**Comment by powercell-hub** [comment]
I had the same issue, the `mini_games` maps worked and the `melee` maps also worked.

As stated in deepmind github https://github.com/google-deepmind/pysc2#list-the-maps
I ran this piece of code to see the lists of known maps `python -m pysc2.bin.map_list`
![Screenshot 2023-10-22 130448](https://github.com/google-deepmind/pysc2/assets/84346193/decea2ab-a318-4593-80bf-2b6d24a0fb46)
As you can see the maps are named under a shorter name than the map files.

In my code removing the LE from the name made it work.
I defined `map_name="AbyssalReef"`
Instead of `map_name="AbyssalReefLE"` 

Hope this can help.
