### ISSUE TITLE
Fast boot

### ISSUE THREAD

**Issue by baptistemanson** [deepmind/pysc2#70]
Hi everyone,

I made a couple of faster algorithms for the shard collecting problem. It takes a very long time to iterate with pysc2, as we have to reboot sc2 + the map + the agents at each change. However, the only component changing is 90% of the time the agent.

As far as I understood the agent communicates to SC2 via protobuff, therefore following a client/server architecture. It seems possible to not have to reset sc2 between iterations.
Any pointers on where to start for this?

Thanks,

**Comment by a3626a** [comment]
`pysc2.sc2_env.reset()` won't reboot startcraft.

**Comment by tewalds** [comment]
The sc2_env isn't that complicated, so if you've got something more specific that you'd like to do, feel free to use the libraries to launch and communicate with the game and parse actions/observations. I don't think we'll be changing the sc2_env though, since the startup time isn't that bad, and would complicate state machine a bunch.

**Comment by tewalds** [comment]
This is a duplicate of #33

**Comment by baptistemanson** [comment]
Thank you everyone!
