### ISSUE TITLE
some questions about replay

### ISSUE THREAD

**Issue by DengpanFu** [deepmind/pysc2#82]
I tried to complete supervised learning from the replays, so i parsed the replay to get feature_layers, available actions, exactly executed actions for every time-step. the core code i used:
```
# controller is the replay game controller
feature = features.Fetures(controller.game_info())
while True:
    controller.step(step_mul)
    obs = controller.observe()
    if obs.player_result:
        break
    available_actions = feature.available_actions(obs.observation)
    exec_actions = []
    for ac in obs.actions:
      try:
        exec_act = feature.reverse_action(ac)
      except ValueError:
        exec_act = features.actions.FunctionCall(0, [])  # no_op
      exec_actions.append(exec_act)
```
Then i found something strange. i print every time-step's action, the following are two of them:
```
Available actios: [0, 1, 2, 3, 4, 9, 335, 336, 451, 343, 344, 452]
Execute actions: [FunctionCall(function=1, arguments=[[11, 43]])]
...
Available actions: [0, 1, 2, 3, 4, 5, 168, 335, 336, 451, 452]
Execute actions: [FunctionCall(function=2, arguments=[[1], [43, 24]]), FunctionCall(function=9, arguments=[]), FunctionCall(function=467, arguments=[[0]])]
...
Available actios: [0, 1, 2, 3, 4, 453, 12, 331, 332, 333, 334, 13, 274, 451, 452]
Execute actions: [FunctionCall(function=451, arguments=[[0], [49, 7]]), FunctionCall(function=451, arguments=[[0], [47, 7]])]
```
I have the following questions:
1. In a time-step, more than one action were actually made and send to the SC2 server(step_mul was set to 1, i got these actions frame by frame), does that means the player played fast and produced more than one action in a very short time and we should predict multi-actions at a times-step ?
2. The second shows that, the actually taken action may be out of the available actions' range, does that means the player could carry out some invalid actions(while the SC2 server will ignore these actions) ?
3. The third shows that, an action can be performed multi-times with different arguments in the same time-step, that's odd, and how can we know which coordinates to predict ?
 
Any suggestion is appreciate. @tewalds

**Comment by tewalds** [comment]
Yes, humans can make actions very quickly, sometimes two within the same ~50ms time slot that is one frame. That can happen either due to them clicking quickly, or due to network lag. For the second frame they selected something (larva) and trained a drone (467) very quickly. Humans are limited by what's valid on their screen, which can change the available actions more quickly than the API can. For your third frame it's 451=Smart, ie right click. They clearly right clicked very quickly, just a few pixels apart. These are things that we don't allow in the api right now, but could relax if it was important. Somehow I doubt it'll ever be important to do two actions in one frame. Such is the challenge of working with human data though.

**Comment by stefanpantic** [comment]
@DengpanFu Would you mind sharing the code you used to parse the replay. I'm trying to do the same thing and have hit sort of a wall.

**Comment by stefanpantic** [comment]
@DengpanFu  Thanks for your reply, I got it working. :smile:
