### ISSUE TITLE
ModuleNotFoundError: No module named 'pysc2.bin'

### ISSUE THREAD

**Issue by boodahgreens** [deepmind/pysc2#87]
I'm sorry, could somebody help me get this running? I've had the full sc2 LOTV installed for years, installed on my second SSD, is that what the problem is. How would I set the path correctly if it is?

**Comment by portersan** [comment]
I believe I had a similar problem.  Mine had nothing to do with Starcraft, rather Python could not find the module pysc2.bin.agent.  It turned out that I had a local installation of anaconda and this conflicted with the Python version into which pip installed all the pysc2 stuff.  The fix for me was to remove the anaconda version from my PATH.  I'd try searching until you find pysc2.bin and that will tell you in which version of Python it was installed.

**Comment by tewalds** [comment]
As portersan said, this is something to do with your python install. One easy thing to try is using a virtualenv install of python so that it is isolated from the rest of your system.

**Comment by Nickrader** [comment]
> I'd try searching until you find pysc2.bin and that will tell you in which version of Python it was installed.

For me I had multiple different python versions installed, and located it in this folder.  (i.e. check the scripts folder of the differenty python folders with numbers)
```C:\Users\YourUsername\AppData\Roaming\Python\Python37\Scripts```

Then using pylauncher was able to specify the python version
``` py -3.7 -m pysc2.bin.agent --map Simple64```

While not the ideal way to setup, it was simple and relatively fast.
